### PR TITLE
Add JSON Marshal/Unmarshal

### PR DESCRIPTION
**Pull request by k315k1010**
@Rhymond
I've waited to be merged #38, but it looks have not updated long time.
I need JSON marshaling/unmarshaling feature for go-money. I've tried to update and fix it.
Could you check this PR?

### CODE REVIEW

**Comment by Rhymond** [comment]
hey @k315k1010, thanks for your PR. I'm not sure how we can make it backwards compatible? I'm more concern about projects who already uses go-money and marshals money in different way, or even default way. Do you think it's going to affect them? If yes, how we can avoid it?

**Comment by k315k1010** [comment]
Hi, @Rhymond 
Thank you for your comment, and I'm sorry that I didn't notice #52 discussion.
As you pointed out, there was not enough consideration for backward compatibility.
I thought of it, but I couldn't come up with a solution other than allowing to inject the JSON marshal / unmarshal functions. I pushed my proposal.
How do you think about it?

**Comment by andradei** [comment]
With Go modules, this can be made v2 (merge the PR and tag it as v2.0.0). It would be nice to have this PR merged.

**Comment by Rhymond** [comment]
HI Both @k315k1010, @andradei,

Sorry for late response, I had some time off. Now then I'm came back we can merge this.
I really like the idea of injection and v2. Couple of things before merging:

---

What do you think about having Marshaler interface? Which has two methods to marshal and unmarshal (same func types as you have now) and to have default Marshaller which has the same functions for default as you did in this PR?
And then we could introduce new method of money which would be called something like `WithMarshaller(m MarshallerInterface)` (or better `WithJSONMarshaller`) which changes the default one. 
When you want to initialise new money with a different marshaller you could do:
```go
m := money.New(100, "GBP")
m.WithMarshaller(yourMarshallerHere)
```
What do you both think? @k315k1010 @andradei 

---

One more issue I see here that we need to make Amount and Currency publicly accessible fields. Without it, you couldn't use them to build your custom marshaller, am I right?

---
One more small thing, could you update tests and instead of having test/test2 rename it to testDefaultMarshal/testCustomMarshal?

**Comment by andradei** [comment]
> What do you think about having Marshaler interface?
I'm not the author of the PR, but I think making another interface isn't ideal because `encoding/json` already has a [Marshaler](https://golang.org/pkg/encoding/json/#Marshaler) and an [Unmarshaler](https://golang.org/pkg/encoding/json/#Unmarshaler) that this PR already makes use of!

That being said, your idea of having a custom marshaler/unmarshaler per `Money` object is great for API design.

With this PR, users can only change the marshal/unmarshal functions at a package level, which isn't good for users:

```go
// On my project I can write:
money.UnmarshalJSONMoneyFunc = ... // And add my own unmarshal function here.
```

So, your API example is great! And there are ways to do it without an extra interface.

---

Also, the names in this PR could be simplified:

`func defaultUnmarshalJSONMoneyFunc` -> `func defaultUnmarshalJSON`

`var UnmarshalJSONMoneyFunc` -> `var DefaultUnmarshalJSON`.

---

> One more issue I see here that we need to make Amount and Currency publicly accessible fields. Without it, you couldn't use them to build your custom marshaller, am I right?

If you want users to make their own (un)marshaling functions, yes. This is easier said than done, though. User who want to do this would have to wrap (embed) `Money` in their own type since they can't add methods to types of `money` package.

I'd say make a v2 (break compatibility with previous versions) and have one implementation for both `MarshalJSON` and `UnmarshalJSON` that people will have to live with. Keep it simple, it will show all data users will ever want to work with, and there will be no code injection.

This is just my opinion and could be just personal taste instead of objective improvement of this PR. And this PR provides the functionality in a good way.

**Comment by Rhymond** [comment]
@andradei Thanks for the answer, I will create v2 in the next week.

**Comment by k315k1010** [comment]
Hi @Rhymond , @andradei,

Sorry for late response. And thanks for your comments.
I answer about your concerns.

----
> And then we could introduce new method of money which would be called something like WithMarshaller(m MarshallerInterface) (or better WithJSONMarshaller) which changes the default one.
> When you want to initialise new money with a different marshaller you could do:

```go
m := money.New(100, "GBP")
m.WithMarshaller(yourMarshallerHere)
```
> What do you both think?

I think, it's unnecessary.
The Marshal/Unmarshal method is closely related to JSON format(as an interface) **compatibility**.
It should be identical and consistent within each systems that using `Money`.

So, I think there is no needs to change the methods for each `Money` instances.
It also to be cause of bugs that forget to call `WithMarshaller`.

----

> One more issue I see here that we need to make Amount and Currency publicly accessible fields. Without it, you couldn't use them to build your custom marshaller, am I right?

I think it's no need to make Amount and Currency publicly accessible fields.
`CustomUnmarshaller` can use public constructor(`New(amount, code)`), and replace the target value `m *Money` to new value like below:

```go
func customUnmarshalJSON(m *Money, b []byte) error {
	data := make(map[string]interface{})
	err := json.Unmarshal(b, &data)
	if err != nil {
		return err
	}

	ref := New(int64(data["amount"].(float64)), data["currency"].(string))
	*m = *ref

	return nil
}
```

I'll try to fix `defaultMarshaller` in the same way.

----

> One more small thing, could you update tests and instead of having test/test2 rename it to testDefaultMarshal/testCustomMarshal?

Absolutely, you are right.
I will fix them.

----

> Also, the names in this PR could be simplified:

`func defaultUnmarshalJSONMoneyFunc -> func defaultUnmarshalJSON`

`var UnmarshalJSONMoneyFunc -> var DefaultUnmarshalJSON.`

I agree. I'll fix them too.

**Comment by k315k1010** [comment]
@Rhymond , @andradei,

I've fixed the issues. Please check them.
Thank you.

**Comment by Rhymond** [comment]
LGTM, merged to master, Will create new release soon

**Comment by k315k1010** [comment]
@Rhymond 

Thank you so much!

**Comment by maeglindeveloper** [comment]
Yeahhhhh thanks a lot ! 👍

**Pull request merged**
