### PR TITLE
Added ISO 4217 numeric codes for currency

### PR DESCRIPTION
**Pull request by nvjkmr**

### CODE REVIEW

**Comment by nvjkmr** [comment]
Picked from this wiki page: https://en.wikipedia.org/wiki/ISO_4217

**Comment by Rhymond** [comment]
Thanks for the contribution, could you please resolve conflicts and we will merge it

**Comment by nvjkmr** [comment]
@Rhymond Resolved.

**Comment by hebime** [comment]
@Rhymond Can this be merged? We're looking for this functionality as well. Thank you :)

**Review by xsami — APPROVED** [review]

**Comment by hebime** [comment]
🎉 thank you! 😄

**Pull request merged**
