### PR TITLE
Addition of currency code constants

### PR DESCRIPTION
**Pull request by jamesallured**
See #72 for the original proposal.

This pull request includes the addition of constants for the 168 ISO 4217 currency codes that are currently present in this package.

In addition to adding these, I have updated the map of currencies in `currency.go` for both the key in the map and the currency code in the struct to be returned. Similarly, I have updated the tests to include their usage and updated the examples in the README to include their usage.

Definitely willing to have a discussion about how we include their usage in the README. This is certainly the part of this pull request that I have the most questions about so far. In particular, I worry about causing confusion with the usage of the constants with regards to a consumer of the package adding their own currencies.

### CODE REVIEW

**Comment by jamesallured** [comment]
Closes #72

**Review by lombartec — APPROVED** [review]

**Comment by Rhymond** [comment]
@jamesallured sorry for the late response and thanks for the PR! It is an amazing addition. Do you think it can cause any backwards compatibility issues? Will users with "custom" currencies going to be affected by this change?

**Comment by jamesallured** [comment]
> @jamesallured sorry for the late response and thanks for the PR! It is an amazing addition. Do you think it can cause any backwards compatibility issues? Will users with "custom" currencies going to be affected by this change?

@Rhymond I don't believe it will have any issues with backwards compatibility as these are just additional constants that can be used in place of a string, i.e. `money.GBP` instead of `"GBP"`. Similarly, as these are just additions that cover existing currencies according to ISO 4217, users with custom currencies won't be affected.

**Review by Rhymond — APPROVED** [review]

**Comment by Rhymond** [comment]
@jamesallured thanks for the answer. Let's fix the conflict and I will merge the PR straight in

**Comment by jamesallured** [comment]
@Rhymond Thanks, I've fixed the merge conflicts. I think we're good to go! ✌🏼

**Pull request merged**
