### PR TITLE
added percentage calculation

### PR DESCRIPTION
**Pull request by raoulk**
We needed percentage calculation for our money calculation use cases. Maybe that's interesting for others, too.

### CODE REVIEW

**Comment by raoulk** [comment]
Is compatibility to Go <1.10 mandatory? The math.Round function came with v1.10

**Comment by Rhymond** [comment]
Hey @raoulk 

Thanks for PR and I'm really sorry for late response. I had a bit time off.
Great idea! Maybe of using Math.round you could use our calculator.round function instead? Try it and let me know how it works.

Thanks

**Comment by raoulk** [comment]
Hi @Rhymond ,
I' sorry, too: Our company decided to use something more simple, as we don't need currency in our calculations. Unfortunately, the fork is already deleted from our repository.
I had a quick look on the calculator.round function: It would require some refactoring, and I am not sure if it's worth it to be compatible with some ancient Go versions ;-)
So I let it up to you if you want to use this PR as it is (I'm not even sure if you can do the merge from a non-existing fork)...

**Comment by Rhymond** [comment]
I will close this, if someone needs this feature please reopen.

**Comment by yodiaz87** [comment]
Hello @Rhymond is there any recommended way to calculate Money percentages already?

**Pull request closed without merging**
