### PR TITLE
Get Currency by Numeric Code

### PR DESCRIPTION
**Pull request by Rhymond**
Code changes allow to get the currency by numeric code or a code used to index currencies map. The PR fixes issues with the PR https://github.com/Rhymond/go-money/pull/96

### CODE REVIEW

**Comment by psrajat** [comment]
@Rhymond Do you feel the `CurrencyByNumericCode` will be under performant compared to the [provided fix](https://github.com/Rhymond/go-money/pull/96#issuecomment-1084786914) by @Stocco?

**Comment by Rhymond** [comment]
@psrajat  I don't think so, we're talking about the map of 100 items, trust me Go is fast enough to read from memory and make it barely noticeable. Of course it highly depend on your use case. If each nanosecond (billionth of a second) counts, you could use `Add()` method to add currencies to the list by NumericCode and get it by the code then.

**Comment by psrajat** [comment]
@Rhymond Sorry for getting back late.

> If each nanosecond (billionth of a second) counts

TBF we don't even have this use case as of now. 
But I feel it should be pointed out that iteration performance of a map is quite poor because of the underlying data structure.

I actually ran some benchmarks of `CurrencyByCode()` and `CurrencyByNumericCode()` methods in my local machine and I observe almost a 100x difference.

```go
var result *Currency

func BenchmarkCurrencies_CurrencyByNumericCode(b *testing.B) {
	var currency *Currency
	for n := 0; n < b.N; n++ {
		currency = currencies.CurrencyByNumericCode("932")
	}
	result = currency
}

func BenchmarkCurrencies_CurrencyByCode(b *testing.B) {
	var currency *Currency
	for n := 0; n < b.N; n++ {
		currency = currencies.CurrencyByCode("ZWD")
	}
	result = currency
}
```

```
BenchmarkCurrencies_CurrencyByNumericCode
BenchmarkCurrencies_CurrencyByNumericCode-8   	 1218165	                942.8 ns/op
BenchmarkCurrencies_CurrencyByCode
BenchmarkCurrencies_CurrencyByCode-8          	100000000	        10.59 ns/op
```

A high throughput service which relies on `CurrencyByNumericCode()` can add this bit of optimization.
And I feel it should be the part of the library rather than manually adding the same currencies using `Add()`.

**Comment by psrajat** [comment]
@Rhymond Any thoughts on this?

**Pull request merged**
